services:
  goods-helper-ui:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4173:80"
    restart: unless-stopped
  goods-helper-bot:
    build:
      context: ./bot
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - goods-helper-ui
    restart: unless-stopped

